<?php

namespace PartyPlanner\EventBundle\Repository;

/**
 * EntranceFeeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntranceFeeRepository extends \Doctrine\ORM\EntityRepository
{
}
