party_planner_core:
    resource: "@CoreBundle/Controller/"
    type:     annotation
    prefix:   /

event:
    resource: "@EventBundle/Controller/"
    type:     annotation
    prefix:   /

user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /
