# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        PartyPlanner\UserBundle\Entity\User:
            algorithm: bcrypt

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        pgsql:
            entity:
                class: UserBundle:User
                property: username

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern: ^/
            provider: pgsql
            anonymous: ~
            form_login:
                login_path: signin
                check_path: signin
                default_target_path: home

            logout:
                path: signout
                target: home

            # activate different ways to authenticate

            # https://symfony.com/doc/current/security.html#a-configuring-how-your-users-will-authenticate
            # http_basic: ~

            # https://symfony.com/doc/current/security/form_login_setup.html
            # form_login: ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }
